version: "3"
services:
  backend:
    container_name: backend
    build: .
    image: mrphyaesonethwim41488934988931/strapi-test
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: db
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PORT: ${DATABASE_PORT}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      NODE_ENV: ${NODE_ENV}
    volumes:
      - strapi-upload:/opt/app/public
      - ./:/opt/app
      - /opt/app/node_modules
    ports:
      - "1337:1337"
    networks:
      - strapi-conn
    depends_on:
      - db
    command: npm run start

  db:
    image: postgres:12.0-alpine
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - strapi-data:/var/lib/postgresql/data/ #using a volume
      #- ./data:/var/lib/postgresql/data/ # if you want to use a bind folder
    ports:
      - "5432:5432"
    networks:
      - strapi-conn

volumes:
  strapi-data:
  strapi-upload:

networks:
  strapi-conn:
    name: Strapi
    driver: bridge
